import { makeStyles } from "@material-ui/core"

const useImageNodeStyles = makeStyles({
  contentEditable: {
    minHeight: "20px",
    border: "0px",
    resize: "none",
    cursor: "text",
    caretColor: "rgb(5, 5, 5)",
    display: "block",
    position: "relative",
    tabSize: "1",
    outline: "0px",
    padding: "10px",
    userSelect: "text",
    fontSize: "12px",
    width: "calc(100% - 20px)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  placeholder: {
    fontSize: "12px",
    color: "#888",
    overflow: "hidden",
    position: "absolute",
    textOverflow: "ellipsis",
    top: "10px",
    left: "10px",
    userSelect: "none",
    whiteSpace: "nowrap",
    display: "inline-block",
    pointerEvents: "none",
  },
  "image-caption-container": {
    display: "block",
    position: "absolute",
    bottom: "4px",
    left: "0",
    right: "0",
    padding: "0",
    margin: "0",
    borderTop: "1px solid #fff",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    minWidth: "100px",
    color: "#000",
    overflow: "hidden",
  },
})

export default useImageNodeStyles
